### ISSUE TITLE
can't click on points underneath mastercluster circle

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#101]
I found a point that was close to two stacked points, but when the mastercluster circle was applied (even when it was spiderfied out), you couldn't click on the point underneath until you zoomed in far enough that the point was outside of the mastercluster circle. I'm wondering if there's a setting to allow point clicks through the circle when it's spiderfied out?

Can't click:
![image](https://user-images.githubusercontent.com/16122136/36125698-abf5892a-101a-11e8-8225-ab42f95c4d44.png)

Could click:
![image](https://user-images.githubusercontent.com/16122136/36125805-30e31a58-101b-11e8-92f3-65a0ed3a91ea.png)

**Comment by troddick** [comment]
No, this is not possible. An easy solution is to zoom in one more level to be able to see it or zoom out until the markercluster turns back into a point.
