### ISSUE TITLE
review content and format of download file

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#102]
Can change header names, can add text block at top of file

**Comment by jlbruce** [comment]
Wondering if you can make these modifications (see attached excel doc).
Yellow cells = added or modified text
Red cells = looks like something bad happened to the data
Blue cells = possible to include these fields in download?

Also, can we attach a data and time to the file name, in case they do multiple downloads to the same place, they won't overwrite them? The timestamp and date format don't matter that much to me - if they're downloading SiGL data, they're probably familiar with UTC Military time - so use whatever is easiest.

[SiGL_export_20180226_0924EDT.xlsx](https://github.com/USGS-WiM/SiGL/files/1760737/SiGL_export_20180226_0924EDT.xlsx)

**Comment by kjacobsen16** [comment]
done
