### ISSUE TITLE
replace GL basins layer with new file and citation

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#103]
While searching for the citation for the existing GL basins layer (which doesn't exist), Dave Saad provided an updated GL basins layer based on some more recent hydro delineations. New shapefile is attached...

[GLbasins_updated_20180213.zip](https://github.com/USGS-WiM/SiGL/files/1721328/GLbasins_updated_20180213.zip)

Citation for services page:

U.S. stream networks: Moore, R. B., and Dewald, T. G., 2016, The road to NHDPlus— Advancements in digital stream networks and associated catchments: Journal of the American Water Resources Association 1–10. DOI: 10.1111/1752-1688.12389
Canada stream networks: Ontario Integrated Hydrology Data, 2012, Ontario Ministry of Natural Resources and Forestry, digital data, last accessed on Feb. 13, 2018, at https://www.ontario.ca/data/ontario-integrated-hydrology-data
Catchments were delineated using [USGS National Elevation Dataset](https://pubs.er.usgs.gov/publication/70039555) which included elevation data from the Canada National Topographic Database.

**Comment by esmyers** [comment]
New layer in, just have to add citation
