### ISSUE TITLE
Change background of Site/Project Count

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SiGL#105]
When either count is 0, badges should remain grey.
When count != 0 make it COLOR TO BE DETERMINED.

**Comment by troddick** [comment]
No project count is shown if there are no projects that meet the filters.
![image](https://user-images.githubusercontent.com/1580076/36284844-f0617758-126e-11e8-8f33-479e8aa0780c.png)

**Comment by troddick** [comment]
showing blue for now, for those site counts > 0
![image](https://user-images.githubusercontent.com/1580076/36285245-66e1f226-1270-11e8-8f6e-5f10a0909421.png)

**Comment by troddick** [comment]
closing for now. reopen to change color.
