### ISSUE TITLE
filter modal select menus not overlapping modal borders

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SiGL#131]
![image](https://user-images.githubusercontent.com/2495167/39528103-d074d4f2-4de8-11e8-8066-b0062c7fb4c3.png)

this is the <ss-multiselect-dropdown/> directive in filterComponent.html,  The .dropdown-menu is not overflowing the border of the modal.  

The other form-controls (project org, and search by project name) are overflowing the modal properly.

**Comment by kjacobsen16** [comment]
fixed
