### ISSUE TITLE
Add contact info to about

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SiGL#154]
Lisa Reynolds Fogarty
U.S. Geological Survey
Upper Midwest Water Science Center, Lansing MI
Office: (517) 887-8968
Fax: (517) 887-8937
Cell: (517) 648-0174
E-mail: lrfogart@usgs.gov

**Comment by esmyers** [comment]
@HansVraga we are currently pointing users to the sigl team email address.  Is the contact info above still a viable issue?

**Comment by HansVraga** [comment]
Nope. Good call to go with the sigl address.
