### ISSUE TITLE
Remediate Vulnerability: Outdated Javascript Library

### ISSUE THREAD

**Issue by aaronstephenson** [USGS-WiM/SiGL#165]
Acunetix scan reports this app is using Leaflet 1.3.1 and should be updated.

Note that this scan was of **SiglMapper**, but I am unable to find a repo with that name.

**Comment by aaronstephenson** [comment]
This is an "info" level vulnerability, so no rush to remediate it right now.

**Comment by aaronstephenson** [comment]
Closing because we can ignore "info" level vulnerabilities.

**Comment by esmyers** [comment]
Also we are using leaflet 1.7 now, so this should not be flagged in the future.
