### ISSUE TITLE
Remove Sigl from Toad and redirect traffic

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SiGL#176]
Unfortunately, my account doesn't have admin rights to delete or move files on Toad, but here are the things we need to do:
Addresses on Toad that will need redirects to sciencebase page or sigl retirement page if we choose to build one:

***Page redirects***
- [x] - sigl.wim.usgs.gov/sigl
- [x] - sigl.wim.usgs.gov/siglDMS
- [x] - sigl.wim.usgs.gov/siglMapper
- [x] - sigl.wim.usgs.gov/SiGLServices

***Toad Applications to remove/archive***
- [x] LaMPServices x2
- [x] SiglServices
- [x] SiglProxiesNew
- [x] anything else with SiGL or Lamp

**Comment by esmyers** [comment]
Status of SiGL AWS Assets

***WIM Main:***
- [ ] SiGLDev (EC2) -- (stopped) can be removed by sysops if needed
- [ ] lampnew (RDS) -- Can be removed by sysops 
- [ ] [sigl.wim.usgs.gov](http://sigl.wim.usgs.gov/) (S3) -- contents deleted from bucket 
- [ ] [sigdev.wim.usgs.gov](http://sigdev.wim.usgs.gov/) (S3) -- contents deleted from bucket

***WIM Prod:***
- [ ] SIGL (RDS)  -- Can be removed by sysops as soon as data archive release is complete

**Comment by aaronstephenson** [comment]
@esmyers what is the sciencebase page URL?

**Comment by esmyers** [comment]
https://www.sciencebase.gov/catalog/item/632a1b9ad34e71c6d67b908d.  It won't be accessible to the public until approved though.

**Comment by aaronstephenson** [comment]
SiGLDev and lampnew are now backed up and terminated. I will work on the Toad files next.

**Comment by aaronstephenson** [comment]
I don't see "LaMPServices x2" on Toad. Might it be under another name, or in another account?

**Comment by aaronstephenson** [comment]
I zipped up the entire contents of D:\sigl on Toad (fonts, secrets, sigl, SiGLDMS, SiglMapper, SIGLProxiesNew, SiGLServices, sigltest), then deleted all the files in that folder except the web.config which handles the 301 redirect to that ScienceBase URL for any requests to sigl.wim.usgs.gov and sigltest.wim.usgs.gov. Where should I put this zip archive?

I also noticed some sigl/lamp folders in D:\Applications (LaMPServices, SiglProxiesNew, SiGLServices, and LaMPServices.zip). Should those be archived somewhere too?

I didn't see any other sigl/lamp files on Toad.

**Comment by aaronstephenson** [comment]
Bah, I just realized you didn't want me to tear down the prod stuff yet. I restored the apps/services/proxies. Easy enough to get rid of them again, tho.

**Comment by esmyers** [comment]
You could place the folder in sharepoint.  If you want to create a new folder for the Toad archive that's fine, otherwise maybe there's an existing folder that would make sense to put it in.  https://doimspp.sharepoint.com/sites/GS-UMidWIM/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FGS%2DUMidWIM%2FShared%20Documents%2FProjects%2FSiGL%20%28LaMP%29&viewid=144f35a1%2D90d4%2D4ed2%2D9f31%2D521ec6887304

**Comment by aaronstephenson** [comment]
@esmyers Has the data archive release been completed? Just wondering when I should take down the remaining assets. Thanks.

**Comment by esmyers** [comment]
@aaronstephenson.  Thanks for checking.  It hasn't been completed yet.  It is in the Bureau approval stage at the moment.

**Comment by aaronstephenson** [comment]
Now that the ScienceBase archive is available, I have removed all these assets.
