### ISSUE TITLE
close popup x click not removing highlight

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGL#33]

**Comment by esmyers** [comment]
I know what's happening, but I don't know how yet.  The sidebar highlight seems to be adding a highlight graphic and so is the map click event.  Only the map click highlight is getting removed on popupclose.  Will have to dig into this a little more closely.

**Comment by troddick** [comment]
may have to check for all highlight layers to remove on popupclose?
Let me know if you want me to look at it, since I'm the one that created this bug in the first place. :)

**Comment by troddick** [comment]
One thing I just noticed clicking around is that the highlight does not go away only on the initial geojson layer. Once I filter the map and then click on a site and close the popup, the highlight layer does go away too.

**Comment by troddick** [comment]
fixed.
