### ISSUE TITLE
site filter combination returns a project with no filtered sites

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGL#38]
Need to look at the endpoint in the services. the request returns a project, but none of it's sites are in the filtered results and the map shows nothing (as it should). But there should be no project that matches this filter since it's a site level filter.
![image](https://user-images.githubusercontent.com/1580076/34214771-11cc68c2-e569-11e7-9191-a4c85ab4e498.png)

**Comment by esmyers** [comment]
Is this related to  mapservice.ts line 274?  Seems like the app still think the sites are there.

**Comment by troddick** [comment]
No, this is definitely related to the endpoint. 
Doing this sql query against the db returns no projects:

    SELECT DISTINCT p.project_id
    FROM project p
    left join site s on p.project_id = s.project_id
    left join site_parameters sp on s.site_id = sp.site_id
    left join site_resource sr on s.site_id = sr.site_id
    where s.lake_type_id = 3 AND 
    sp.parameter_type_id = 45 AND
    sr.resource_type_id = 18;

which is what this FilteredProjects endpoint is essentially supposed to be doing. It starts with a query object to hold all the projects, and then narrows down that list based on the presence of parameters passed in. Some how a project is getting returned even though none of it's sites match any of the parameters passed in the filter.

**Comment by troddick** [comment]
I have no idea what's going on with this endpoint. It's weird.
/Projects/FilteredProjects?Parameters=45&ResComp=1&Lake=3  --> returns 
![image](https://user-images.githubusercontent.com/1580076/34230786-fa4f4cb0-e59e-11e7-9123-645415edb023.png)

/Projects/FilteredProjects?Parameters=45&ResComp=1&Lake=2  --> returns 
![image](https://user-images.githubusercontent.com/1580076/34230875-623a20d4-e59f-11e7-9ec2-8b3cd234eac3.png)

Other combinations return the same problem. But if I change any of these to the filtered Sites endpoint, they work as expected. The code within is almost identical (Filter through the projects and look at the sites and down into the related site things vs filter through the sites and look up at the containing projects)

 /Sites/FilteredSites?Parameters=45&ResComp=1&Lake=3 and 
/Sites/FilteredSites?Parameters=45&ResComp=1&Lake=2
both return empty arrays

I'm going to table this for now.

**Comment by troddick** [comment]
Just needed to sleep on it. Fixed. (after spending hours on this yesterday, it took me 10 min this morning)

**Comment by troddick** [comment]
never mind.. My solution doesn't return projects with no sites, back to the drawing board.

**Comment by troddick** [comment]
OK. Got it now.
