### ISSUE TITLE
update styling to be like SWTrends or Sparrow

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGL#46]
- tabs in upper right corner
- carets on sidebar accordions
 etc...

New Sparrow https://test.wim.usgs.gov/SparrowGreatLakesV2/
SWTrends https://nawqatrends.wim.usgs.gov/swtrends/

**Comment by troddick** [comment]
updated navbar to have the pull-right buttons in upper right corner

**Comment by HansVraga** [comment]
Ensure to include USGS footer links on bottom of sidebar.
Look to eliminate any "WiM" in favor of "WIM"
