### ISSUE TITLE
add google analytics

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGL#50]

**Comment by HansVraga** [comment]
Lauren, Tonia, Erik to review the application and decide the main functions that we want to capture as events.

**Comment by troddick** [comment]
These are the events that have been added to the application. We can add/remove from this list, or change the label to be something different. Just my initial run-through:
![image](https://user-images.githubusercontent.com/1580076/34388580-0d0e04a8-eafa-11e7-9430-18470f6d103f.png)
