### ISSUE TITLE
Add Alert to IE users directing them to a different browser

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SiGL#51]

**Comment by troddick** [comment]
I got IE to work, but performance is not as good as Chrome or Firefox. I will add a comment in the Disclaimer section regarding for best performance, use Chrome or Firefox.

**Comment by troddick** [comment]
Added to the Disclaimer: 
"This web application functions best in Chrome, Firefox, or Safari. Internet Explorer works but with slower performance."

**Comment by HansVraga** [comment]
Going to explicitly test Edge, and tweak the language accordingly.

**Comment by HansVraga** [comment]
Done.
