### ISSUE TITLE
add disclaimer to Additional info

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGL#54]
look to https://streamstats.usgs.gov/ss
in the About modal

**Comment by HansVraga** [comment]
Ensure we credit open source projects, include the USGS disclaimers.

**Comment by troddick** [comment]
![image](https://user-images.githubusercontent.com/1580076/34391315-6b411974-eb0a-11e7-9c55-93245f94c677.png)

Added. May need to be modified...
