### ISSUE TITLE
Add Public web/map service URLs in interfact/documentation

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGL#55]
same location as disclaimer

**Comment by troddick** [comment]
add metadata link

**Comment by troddick** [comment]
Need more info as to what should be on this tab. 
![image](https://user-images.githubusercontent.com/1580076/34391299-5197af1a-eb0a-11e7-9c50-9cfdbb2458a5.png)

**Comment by troddick** [comment]
@jlbruce

**Comment by jlbruce** [comment]
Updated text and feedback on About section here:
https://docs.google.com/document/d/16FCKv2vVM8w7vEEG1y3xGzKj1hd9OUf2WlFya8mLJDM/edit?usp=sharing

**Comment by troddick** [comment]
move bottom section of disclaimer (starting at credits to libs) to the Metadata tab. Use a different word than "Metadata" for this tab.

**Comment by HansVraga** [comment]
Picking up this effort in #82
