### ISSUE TITLE
side panel loading div won't stop, filter won't resolve

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/SiGL#60]
Hans Vraga [07:48] 
After clicking on a site, clicking on that site's project (Project Name: US EPA GLNPO Water and Biology Monitoring Programs) I tried to filter by that org.

[07:48] 
the side panel loading div doesn't stop....
![image](https://user-images.githubusercontent.com/12058013/34412568-a7c90656-eba3-11e7-87a7-a93c2bf6d713.png)

**Comment by troddick** [comment]
fixed.
