### ISSUE TITLE
no scrolling available in bottom project/site pane

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#66]
Scrolling isn't available in the the bottom project/site pane (I'm not sure what you're calling it, sorry!), and this leads to two issues:

1 - The first time I pulled up the bottom pane to fit more information, I happened to place it perfectly between two text lines, both on the Site Details and Parameters Sampled views. I tried to scroll, since I knew there was more info, but my only option was to stretch it up further. But my fear is that new users won't know that there's more information below, since there is no scroll bar or other visual cue for look for more.

Also, the lack of ability to scroll in this pane is going to be a problem, as some projects have LONG lists of pubs and data sources (and project descriptions) that will never be able to fit in the max pane space. It would be great to let the user choose their ideal balance between pane expansion and scrolling.

For example, for one project that had a long description, my browser let me pull the pane up beyond the browser edge to expose the full content extent, but after I released it (the expansion bar was now above the browser display edge and out of sight), I couldn't grab it again to close the pane, and I had to reload the map and start over.

**Comment by troddick** [comment]
We had not created an issue for this (thought I did), but @mitch-wim  has been working on this. We definitely need a scrollbar in that lower resizable div.

**Comment by troddick** [comment]
closing as this is referenced in #81
