### ISSUE TITLE
map drag sometimes flies way further than you want it to

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#67]
Sorry, this is probably something you're going to need to see in action, but when I'm moving around the map using the click-and-drag with my mouse, sometimes when I let go it flies way off - much further and much faster than I was moving - often so far and fast that the map display takes quite a while to catch up (and by then, I have no idea where I am).

Maybe it's me, but I'm having to really concentrate to carefully and cautiously wait for any map motion to stop before I let go.

**Comment by troddick** [comment]
Cannot duplicate. Will need a demonstration

**Comment by troddick** [comment]
Able to duplicate. Can't find the right search term to find others that have had this problem or possible solutions
