### ISSUE TITLE
add "Find my location" and "Default extent" map buttons

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#68]
Given the issues that I'm having with the map drag, it would really be helpful if we could add the "Find my location" and "Default extent" map buttons that I've seen on the NAQWA Trends and SPARROW maps. Hopefully that's an easy add. Thanks!

**Comment by troddick** [comment]
![image](https://user-images.githubusercontent.com/1580076/34674650-5b01ed22-f44c-11e7-9b74-a2c03c997695.png)

**Comment by troddick** [comment]
Default extent most important of two. Both would be nice though

**Comment by troddick** [comment]
Default extent added
