### ISSUE TITLE
adjust Huron point color slightly

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#69]
This is a tiny styling thing, but when you zoom in and are looking at single semi-transparent points, it's a little difficult to tell the difference between a Huron (maroon) and Michigan (tan) point. I really like the new semi-transparent site display, but we just need to tweak the color a little to make them distinct when they're not full strength. The easiest might be to make Huron a little redder, since we need to keep Michigan tan enough to separate from Erie's yellow sites, but I'll leave it to you to resolve.

**Comment by troddick** [comment]
made it redder.
