### ISSUE TITLE
create new instance with geoserver installed

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/SiGL#7]

**Comment by aaronstephenson** [comment]
I launched a new Ubuntu 16.04 EC2 instance for you, available at 52.21.226.149. Feel free to install [GeoServer](http://geoserver.org/release/stable/) (current version is 2.11.1 http://sourceforge.net/projects/geoserver/files/GeoServer/2.11.1/geoserver-2.11.1-bin.zip).
