### ISSUE TITLE
unwanted field titles showing up for Contacts and Pubs lists

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#71]
Looks like the Contacts list (and Pubs)(maybe Data, too - I couldn't find a point with multiple data items) is pulling in an unwanted field title for all items after the first one: "Contact(2)" "Publications(2)", etc.

Also, since we're here, the contact's organization should display the full org name (org, division, and section fields) - right now it looks like it's just grabbing the first org field.

![image](https://user-images.githubusercontent.com/16122136/34643306-c52b4470-f2e7-11e7-8c9a-8e0a0f712ae7.png)

**Comment by troddick** [comment]
Erik added that on purpose to give a count of contacts. I'm not sure if he wanted to keep it in there or was just testing various angular capabilities. I can remove the "Contact(#)" line.

In regards to the full org name, this is the way the existing sigl mapper handles the contact org name. Just the org name shows. (see image) But, all the required information comes back in the endpoint, so it is an easy addition to add the division and section name if any. I will do that.
![image](https://user-images.githubusercontent.com/1580076/34675269-adfa47b6-f44e-11e7-91a6-6d122eccf5b0.png)

**Comment by troddick** [comment]
fixed.
