### ISSUE TITLE
revise post-filter display

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#74]
I'm trying to think of ways to explain/emphasize that some filters act on site fields, and some act on project fields. Would it be possible to change the post-filter display (image below) to be split? So instead of "Map filterd by" and listing everything, it would say:

Project filters applied:
(listing)

Site filters applied:
(listing)

Also, styling-wise, please use a smaller text site - the "Map filterd by" message is huge!

![image](https://user-images.githubusercontent.com/16122136/34643707-81e3de5a-f2ee-11e7-8766-700282b5b26a.png)

**Comment by troddick** [comment]
done
