### ISSUE TITLE
additional map layers are missing

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#75]
I thought I remembered you guys saying that Erik had finished adding these, but I don't see them?

**Comment by troddick** [comment]
This is related to #63 . There is currently a horizontal scroll bar in the test app along the bottom of the whole window. If you were to scroll all the way to the right, you will see in the upper right corner, the button to show the additional layers. @mitch-wim  fixed the scroll bar, but now there's a related issue with the whole window snapping over when the browswer window width is reduced (causing the sidebar to collapse into a 3 bar menu).

**Comment by jlbruce** [comment]
Thanks - I didn't think to check the horizontal scroll bar (the old mapper always used to load just bigger than my browser, so I'm conditioned to ignore them when it comes to SiGL)!

FYI, in SPARROW and NAWQA Trends, the map layers are located in the left collapsible side bar, and SPARROW even has a transparency slider (cool, but not required). Would the side bar be a better location for these since we're going to need the explanation in the upper right corner?

Also, I think we're going to need to be able to turn off the SiGL sites layer - that was something that has confused users in the past, so we added it as a layer that could be turned off.

**Comment by HansVraga** [comment]
- [ ] Moving Layers under an accordion in the left-hand menu
- [ ] Adding Explanation

**Comment by troddick** [comment]
done and done.
