### ISSUE TITLE
add "Last updated" date into the project/site pane

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#76]
A while ago, we started collecting the date the DMS record was last updated. I don't think we ever added it to the old SiGL mapper, but we wanted to. Can it be added now? Maybe in line with the top tabs (Project Summary, Data/Pubs, etc.), but aligned far right?

**Comment by troddick** [comment]
I can add the last updated date, but I cannot add it to the end of the tabs in that same line. That is a library we are using for tabs, which consists of a <ul> tag (unordered list) with <li> (list items) that make up those tabs. I cannot add a <span> or <div> inside of a <ul>. It will only except a <li> which will create another tab. 
I could put it inside the Project Summary tab as the first item or after the Name.

**Comment by troddick** [comment]
Added it right under the Project name. Can change if you want it somewhere else.
![image](https://user-images.githubusercontent.com/1580076/34776777-8f4d2460-f5dd-11e7-98a3-c5575ae38be0.png)
