### ISSUE TITLE
Add dynamic content to the About Information

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/SiGL#77]
3rd paragraph: 
"SiGL project and site information is voluntarily provided and managed by federal and state agencies, municipalities, Tribes, universities, and nonprofit organizations. As of January 1, 2018, SiGL contained {{300}} projects and {{12,241}} sites from {{106}} organizations."

Everything in {{ ... }} should be dynamically brought in from the services.

**Comment by jlbruce** [comment]
Yay!!! It's awesome that this can be done!

And don't forget that the date {{January 1, 2018}} needs to be updated, too.

**Comment by troddick** [comment]
Done.
