### ISSUE TITLE
Updates to the About window

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#86]
Documented [here](https://docs.google.com/document/d/1NOGt35zX3iKO1VzG9H4Q4i8zy2y-zC1k-dAazwZ88AA/edit?usp=sharing) with notes and questions. I need to track down a few sources.

**Comment by troddick** [comment]
- [ ] Make this link to Services tab: "If you would like to utilize SiGL’s public web services, please visit our  [SiGL Services Documentation tab ] for more information. " 

- [ ]  Make mailTo link: "If you have questions or comments, or would like to have your data included in the SiGL, please contact sigl@usgs.gov"

- [ ]  Add at bottom of Disclaimer tab: SiGL Data Disclaimer: "SiGL project and site information is voluntarily provided and managed by federal and state agencies, municipalities, Tribes, universities, and nonprofit organizations. The USGS takes no responsibility for the accuracy or completeness of information provided by other entities.
This web application functions best in Chrome, Firefox, or Safari. Internet Explorer works but with slower performance."

- [ ] Fix spelling Servies Tab: "Link to EPA Areas of [Concern] REST Services: EPA Areas of [Concern REST Services"

- [ ] Address Ceded Tribal Boundaries and Tribal Reservation Boundaries services location.

**Comment by jlbruce** [comment]
Small edit to text in third check box...
"The USGS **assumes** no responsibility..."

**Comment by jlbruce** [comment]
Citation to follow AOC layer:
U.S Environmental Protection Agency, 2014, Great Lakes Areas of Concern (AOCs) shapefile, no metadata available. Originally downloaded from U.S. EPA website, no longer available as a single file. As of February 12, 2018, individual AOC boundary shapefiles were available at [https://www.epa.gov/great-lakes-aocs/list-great-lakes-aocs-and-contacts](https://www.epa.gov/great-lakes-aocs/list-great-lakes-aocs-and-contacts)

**Comment by troddick** [comment]
Need to look into how to add these via services (@esmyers )
- ceded tribal boundaries: https://data.glifwc.org/ceded/
 link under map to "GLIFWC Web Map Services (WMS) - Get Capabilities":
   http://wms.glifwc.org/?service=wms&request=getcapabilities
- tribal reservation boundaries: https://catalog.data.gov/dataset/bia-indian-lands-dataset-indian-lands-of-the-united-states

**Comment by esmyers** [comment]
Working on getting that WMS in, although it's not cooperating at the moment.
Also, bullet point #2 points back to our server, so we are already showing the official layer.  Consider point #2 done.

**Comment by esmyers** [comment]
I have the WMS ceded territories layer in, but it is a WMS and obscures the basemap.  I will continue to look around for more information about how to handle this, but we may want to ask how important it is to use their hosted layer?
![image](https://user-images.githubusercontent.com/2495167/36215687-6b4a3386-1172-11e8-9815-8e252c4b922b.png)

**Comment by esmyers** [comment]
From my basic reading WMS must be added as a tilelayer.  I'm going to see if there's another way around it.

**Comment by esmyers** [comment]
![image](https://user-images.githubusercontent.com/2495167/36433324-d8f6c26a-1621-11e8-8728-9b504016bbf7.png)
Figured out how to make the WMS basemap transparent so we can use the GLFWC service now.  Will update the Explanation and About Modal Accordingly
