### ISSUE TITLE
missing GL Basins layer from old SiGL map

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#87]
The old mapper loaded with the 5 Great Lake basins underneath, colored similarly to the points. This is an important layer to include. (And I'm assuming that I need to find a citation for it.)

**Comment by troddick** [comment]
https://gis.wim.usgs.gov/arcgis/rest/services/SIGL/SIGLMapper/MapServer/3

**Comment by esmyers** [comment]
Looking into republishing the basins layer with new data.
