### ISSUE TITLE
review site count toggle

### ISSUE THREAD

**Issue by jlbruce** [USGS-WiM/SiGL#97]
Increase type readability while trying not to increase graphic depth. Consider using point highlight colors to reinforce display comprehension.

**Comment by jlbruce** [comment]
How about something like this?

![image](https://user-images.githubusercontent.com/16122136/36704278-45a565e4-1b25-11e8-8a04-b9663cbee229.png)

I chose WiM blue for the highlight so it would standout from the orange filter background, which links nicely with the map and the filtered site names, which I sampled at #0090fa but you guys would know better.

The orange is: ff9e2a
I'd recommend changing all orange text to match (it's a little redder and a little darker, makes type easier to read).

The gray is: #58595b

**Comment by kjacobsen16** [comment]
@jlbruce did you want it to say 'All Sites' and 'Filtered Sites' instead of 'All' and 'Filtered', or was that what it said before?  This is what I've got now:

![image](https://user-images.githubusercontent.com/35497731/36872121-c6da2104-1d69-11e8-85c6-9698223d75a5.png)

**Comment by jlbruce** [comment]
I did add the extra wording, just to give a little extra clarity about what the toggle was for.

Also, the goal of the re-styling of the button was to make the text a little larger and more readable - ideally without increasing the overall depth much if any. That's why I removed the black border and increased the toggle background height to fill the extra height, added more spacing around the words, increased the type size a little, and vertically centered the type. Any of this you can apply to the toggle styling will go a long way to increasing the readability.
